name: "label"

on:
  pull_request_target: ~

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  content-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true

  conventional-label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: bcoe/conventional-release-labels@886f696738527c7be444262c327c89436dfb95a8 # v1.3.1
        with:
          type_labels: |
            {
              "feat": "Feature",
              "fix": "Fix",
              "ci": "CI",
              "docs": "Docs",
              "refactor": "Refactor",
              "build": "Build"
            }
